In [36]:
import numpy as np
np.random.seed(1)

a = np.random.random((3,3))
b = np.array(a, dtype="float64")    # 转成矩阵(ndarray)形式, copy形式
c = np.asarray(a, dtype="float64")  # 引用形式
a[2] = 222

In [37]:
print("a: ", a)

a:  [[  4.17022005e-01   7.20324493e-01   1.14374817e-04]
 [  3.02332573e-01   1.46755891e-01   9.23385948e-02]
 [  2.22000000e+02   2.22000000e+02   2.22000000e+02]]


In [38]:
print("b: ", b)

b:  [[  4.17022005e-01   7.20324493e-01   1.14374817e-04]
 [  3.02332573e-01   1.46755891e-01   9.23385948e-02]
 [  1.86260211e-01   3.45560727e-01   3.96767474e-01]]


In [39]:
print("c: ", c)

c:  [[  4.17022005e-01   7.20324493e-01   1.14374817e-04]
 [  3.02332573e-01   1.46755891e-01   9.23385948e-02]
 [  2.22000000e+02   2.22000000e+02   2.22000000e+02]]


In [30]:
a[1][1] = 222

In [31]:
c

array([[  4.17022005e-01,   7.20324493e-01,   1.14374817e-04],
       [  3.02332573e-01,   2.22000000e+02,   9.23385948e-02],
       [  2.22000000e+02,   2.22000000e+02,   2.22000000e+02]])